In [2]:
import numpy as np
np.random.seed(42)

# Problem 1: Tạo hai ma trận 3x3 với các phần tử integer ngẫu nhiên từ 1 - 10.

In [4]:
# Your code here
matrix1 = np.random.randint(1,11, size=(3,3))
matrix2 = np.random.randint(1,11, size=(3,3))
print(matrix1)
print(matrix2)

[[5 4 8]
 [8 3 6]
 [5 2 8]]
[[ 6  2  5]
 [ 1 10  6]
 [ 9  1 10]]


# Problem 2: Thực hiện phép cộng phần tử, nhân từng phần tử, tích vô hướng với hai ma trận vừa được tạo.


In [11]:
# Your code here
sum_matrix = np.add(matrix1, matrix2)
print(sum_matrix)

mul_matrix = np.multiply(matrix1, matrix2)
print(mul_matrix)

dot_matrix = np.dot(matrix1, matrix2)
print(dot_matrix)

[[11  6 13]
 [ 9 13 12]
 [14  3 18]]
[[30  8 40]
 [ 8 30 36]
 [45  2 80]]
[[106  58 129]
 [105  52 118]
 [104  38 117]]


# Problem 3: VIết hàm nhận vào một mảng Numpy, sau đó trả về tổng tất cả các phần tử của chúng


In [10]:
# Your code 
def sum_of_array(arr):
    total_sum = np.sum(arr)
    return total_sum
    
array = np.array([[1, 2, 3], [4, 5, 6]])
total = sum_of_array(array)
print("Tổng của mảng là:", total)


Tổng của mảng là: 21
